const express = require('express');
const router = express.Router();

const BPRoutes = require('./businesspartnerRoutes');
const OrderRoutes = require('./orderRoutes');
const SalesQuotationRoutes = require('./salesQuotationRoutes');
const PurchaseQuotationRoutes = require('./purchaseQuotationRoutes');
const PurchaseRequestsRoutes = require('./PurchaseRequestsRoutes');
const ItemRoutes = require('./itemRoutes');
const ServiceRoutes = require('./serviceRoutes');
const WareHousesRoutes = require('./WareHousesRoutes');
const PurchaseOrderRoutes = require('./purchaseOrderRoutes');
const ProjectRoutes = require('./projectRoutes');
const ItemPricesRoutes = require('./ItemPricesRoutes');
const DimensionRoutes = require('./DimensionsRoutes');
const ProfitCenterRoutes = require('./ProfitCenterRoutes');
const TaxCodeRoutes = require('./taxCodeRoutes');
const AttachmentRoutes = require('./attachmentRoutes');
const PurchaseDeliveryNote = require('./purchaseDeliverytNoteRoutes');
const OtherRoutes = require('./otherRoutes');

router.use('/business-partners', BPRoutes);
router.use('/orders', OrderRoutes);
router.use('/quotations', SalesQuotationRoutes);
router.use('/purchase-orders', PurchaseOrderRoutes);
router.use('/purchase-quotations', PurchaseQuotationRoutes);
router.use('/purchase-requests', PurchaseRequestsRoutes);
router.use('/SpecialPrices', ItemPricesRoutes);
router.use('/items', ItemRoutes);
router.use('/services', ServiceRoutes);
router.use('/tax-code', TaxCodeRoutes); 
router.use('/warehouses', WareHousesRoutes); 
router.use('/projects', ProjectRoutes);
router.use('/dimensions', DimensionRoutes);
router.use('/profit-centers', ProfitCenterRoutes);
router.use('/attachments', AttachmentRoutes);
router.use('/purchase-delivery-notes', PurchaseDeliveryNote);
router.use('/others', OtherRoutes);

module.exports = router;